<a href="https://colab.research.google.com/github/VenuMadhav-IN18/Machine-Learning/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [63]:
df=pd.read_csv('diabetes_data.csv')

In [64]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,NaN,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0

In [65]:
df.shape

(768, 9)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               728 non-null    float64
 1   Glucose                   722 non-null    float64
 2   BloodPressure             735 non-null    float64
 3   SkinThickness             726 non-null    float64
 4   Insulin                   735 non-null    float64
 5   BMI                       729 non-null    float64
 6   DiabetesPedigreeFunction  734 non-null    float64
 7   Age                       735 non-null    float64
 8   Outcome                   739 non-null    float64
dtypes: float64(9)
memory usage: 54.1 KB

In [67]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,728.000000,722.000000,735.000000,726.000000,735.000000,729.000000,734.000000,735.000000,739.000000
mean,3.912088,120.671745,68.927891,20.632231,80.268027,32.028807,0.467578,33.308844,0.341001
std,3.382204,31.982858,19.590744,16.012616,116.198612,7.904681,0.325979,11.727195,0.474367
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.238250,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,29.000000,32.000000,0.368000,29.000000,0.000000
75%,6.000000,140.750000,80.000000,32.000000,130.000000,36.600000,0.622750,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [68]:
# Null Values in Each Column
df.isnull().sum()

Pregnancies                 40
Glucose                     46
BloodPressure               33
SkinThickness               42
Insulin                     33
BMI                         39
DiabetesPedigreeFunction    34
Age                         33
Outcome                     29
dtype: int64

In [69]:
# Outlier Detection
q1=df['Pregnancies'].quantile(0.25)
q3=df['Pregnancies'].quantile(0.75)
IQR=q3-q1
lowerlimit=q1-1.5*IQR
upperlimit=q3+1.5*IQR

In [70]:
df[(df['Pregnancies']<lowerlimit) | (df['Pregnancies']>upperlimit)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
88,15.0,NaN,70.0,32.0,110.0,37.1,0.153,43.0,1.0
159,17.0,163.0,72.0,41.0,114.0,40.9,0.817,47.0,1.0
298,14.0,100.0,78.0,25.0,184.0,36.6,0.412,46.0,1.0
455,14.0,175.0,62.0,30.0,0.0,33.6,0.212,38.0,1.0

In [71]:
df['Pregnancies']=df['Pregnancies'].fillna(df['Pregnancies'].median())
# replaced the NULL Values with the Median ...why median is there is some outliers

In [72]:
df['Pregnancies'].value_counts()
# The aim is to check how many 0 pregenices..we didn't replace them because they are valid

Pregnancies
1.0     124
3.0     111
0.0     101
2.0     100
4.0      66
5.0      54
6.0      47
7.0      43
8.0      37
9.0      28
10.0     24
11.0     11
13.0      9
12.0      9
14.0      2
17.0      1
15.0      1
Name: count, dtype: int64

In [73]:
# Outlier Detection
q1=df['Glucose'].quantile(0.25)
q3=df['Glucose'].quantile(0.75)
IQR=q3-q1
lowerlimit=q1-1.5*IQR
upperlimit=q3+1.5*IQR

In [74]:
df[(df['Glucose']<lowerlimit) | (df['Glucose']>upperlimit)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
75,1.0,0.0,48.0,20.0,0.0,24.7,0.140,22.0,0.0
182,1.0,0.0,74.0,20.0,23.0,27.7,0.299,21.0,0.0
342,1.0,0.0,68.0,35.0,0.0,32.0,0.389,22.0,0.0
349,5.0,0.0,80.0,32.0,0.0,41.0,0.346,37.0,1.0
502,6.0,0.0,68.0,41.0,0.0,39.0,0.727,41.0,1.0

In [76]:
df['Glucose']=df['Glucose'].replace(0.0,np.nan)

In [77]:
df['Glucose']=df['Glucose'].fillna(df['Glucose'].median())

In [78]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1.0,85.0,66.0,29.0,0.0,NaN,0.351,31.0,0.0
2,8.0,183.0,64.0,0.0,0.0,23.3,0.672,32.0,1.0
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0.0
4,0.0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0
...,...,...,...,...,...,...,...,...,...
763,10.0,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0.0
764,3.0,122.0,70.0,27.0,0.0,36.8,0.340,27.0,0.0
765,5.0,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0.0
766,1.0,126.0,60.0,0.0,0.0,30.1,0.349,47.0,1.0
767,1.0,93.0,70.0,31.0,0.0,30.4,0.315,23.0,0.0